{-# LANGUAGE DataKinds, FlexibleContexts, MagicHash, NoImplicitPrelude,
             TypeApplications #-}

module Riak.Lenses
  ( adds
  , allowMult
  , amount
  , asis
  , backend
  , base
  , basicQuorum
  , bigVclock
  , booleanValue
  , bucket
  , buckets
  , cells
  , charset
  , chashKeyfun
  , clientId
  , columns
  , consistent
  , content
  , contentEncoding
  , contentType
  , context
  , continuation
  , counterOp
  , counterValue
  , coverContext
  , datatype
  , deleted
  , deletedvclock
  , desc
  , df
  , docs
  , done
  , doubleValue
  , dw
  , endIncl
  , endKey
  , entries
  , errcode
  , errmsg
  , field
  , fieldName
  , fields
  , filter
  , fl
  , flagOp
  , flagValue
  , function
  , gsetOp
  , gsetValue
  , hasPostcommit
  , hasPrecommit
  , head
  , hllOp
  , hllPrecision
  , hllValue
  , ifModified
  , ifNoneMatch
  , ifNotModified
  , includeContext
  , increment
  , index
  , indexes
  , interpolations
  , ip
  , key
  , keys
  , keyspaceDesc
  , lastMod
  , lastModUsecs
  , lastWriteWins
  , linkfun
  , links
  , lowerBound
  , lowerBoundInclusive
  , mapOp
  , mapValue
  , maxResults
  , maxScore
  , maybe'allowMult
  , maybe'asis
  , maybe'backend
  , maybe'basicQuorum
  , maybe'bigVclock
  , maybe'booleanValue
  , maybe'bucket
  , maybe'charset
  , maybe'chashKeyfun
  , maybe'consistent
  , maybe'content
  , maybe'contentEncoding
  , maybe'contentType
  , maybe'context
  , maybe'continuation
  , maybe'counterOp
  , maybe'counterValue
  , maybe'coverContext
  , maybe'datatype
  , maybe'deleted
  , maybe'deletedvclock
  , maybe'df
  , maybe'done
  , maybe'doubleValue
  , maybe'dw
  , maybe'endIncl
  , maybe'endKey
  , maybe'filter
  , maybe'flagOp
  , maybe'flagValue
  , maybe'gsetOp
  , maybe'hasPostcommit
  , maybe'hasPrecommit
  , maybe'head
  , maybe'hllOp
  , maybe'hllPrecision
  , maybe'hllValue
  , maybe'ifModified
  , maybe'ifNoneMatch
  , maybe'ifNotModified
  , maybe'includeContext
  , maybe'increment
  , maybe'key
  , maybe'keyspaceDesc
  , maybe'lastMod
  , maybe'lastModUsecs
  , maybe'lastWriteWins
  , maybe'linkfun
  , maybe'mapOp
  , maybe'maxResults
  , maybe'maxScore
  , maybe'minPartitions
  , maybe'modfun
  , maybe'nVal
  , maybe'name
  , maybe'node
  , maybe'notfoundOk
  , maybe'numFound
  , maybe'oldVclock
  , maybe'op
  , maybe'paginationSort
  , maybe'phase
  , maybe'pr
  , maybe'presort
  , maybe'pw
  , maybe'query
  , maybe'r
  , maybe'range
  , maybe'rangeMax
  , maybe'rangeMin
  , maybe'registerOp
  , maybe'registerValue
  , maybe'repl
  , maybe'replaceCover
  , maybe'response
  , maybe'returnBody
  , maybe'returnHead
  , maybe'returnTerms
  , maybe'returnvalue
  , maybe'rows
  , maybe'rw
  , maybe'schema
  , maybe'search
  , maybe'searchIndex
  , maybe'serverVersion
  , maybe'setOp
  , maybe'sint64Value
  , maybe'sloppyQuorum
  , maybe'smallVclock
  , maybe'sort
  , maybe'start
  , maybe'startIncl
  , maybe'stream
  , maybe'tag
  , maybe'termRegex
  , maybe'timeout
  , maybe'timestampValue
  , maybe'ttl
  , maybe'type'
  , maybe'unchanged
  , maybe'value
  , maybe'varcharValue
  , maybe'vclock
  , maybe'vtag
  , maybe'w
  , maybe'writeOnce
  , maybe'youngVclock
  , minPartitions
  , modfun
  , module'
  , nVal
  , name
  , node
  , notfoundOk
  , numFound
  , object
  , objects
  , oldVclock
  , op
  , paginationSort
  , partition
  , password
  , phase
  , port
  , postcommit
  , pr
  , precommit
  , preflist
  , presort
  , primary
  , props
  , pw
  , q
  , qtype
  , query
  , r
  , range
  , rangeMax
  , rangeMin
  , registerOp
  , registerValue
  , removes
  , repl
  , replaceCover
  , request
  , response
  , results
  , returnBody
  , returnHead
  , returnTerms
  , returnvalue
  , rows
  , rw
  , schema
  , search
  , searchIndex
  , serverVersion
  , setOp
  , setValue
  , sint64Value
  , sloppyQuorum
  , smallVclock
  , sort
  , start
  , startIncl
  , startKey
  , stream
  , table
  , tag
  , termRegex
  , timeout
  , timestampValue
  , ttl
  , type'
  , unavailableCover
  , unchanged
  , updates
  , upperBound
  , upperBoundInclusive
  , user
  , usermeta
  , value
  , varcharValue
  , vclock
  , vtag
  , w
  , writeOnce
  , youngVclock
  ) where

import Proto.Riak_Fields
